[workspace]
authors = ["Anna Monson <agm0047@uah.edu>"]
channels = ["conda-forge"]
name = "408-HW2"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
ipykernel = ">=7.2.0,<8"
pip = ">=26.0.1,<27"
numpy = ">=2.4.2,<3"
geopandas = ">=1.1.2,<2"
pandas = ">=3.0.0,<4"
folium = ">=0.20.0,<0.21"
